# Load bashrc if one exists
[ -f ~/.bashrc ] && . ~/.bashrc

# Load bash completion
[ -f `brew --prefix`/etc/bash_completion ] && . `brew --prefix`/etc/bash_completion

export PATH="$HOME/.poetry/bin:$PATH"
